export const String  = {
    welcomeBack: 'Welcome back',
    createAccount: 'Create an Account',
    login: 'Log in',
    signUp: 'Sign Up',
    logOut: 'Log out',
    forgotPassword: 'Forgot Password?',
    emailLable:'Email',
    email: 'email',
    nameLable: 'Name',
    name: 'name',
    passwordLable: 'Password',
    password: 'password',
    rememberMe: 'Remember me',
    loginWithFacebook: 'Login with Facebook',
    loginWithGoogle: 'Login with Google',
    loginWithApple: 'Login with Apple',
    orLogin: 'Or login with',
    orSignUp: 'Or sign up with',
    namePlaceholder: 'Enter your User name',
    emailPlaceholder: 'Enter your email',
    passwordPlaceholder: 'Enter your password',
    emailRequired: 'Email is required',
    nameRequired: 'Name is required',
    passwordRequired: 'Password is required',
    invalidEmail: 'Invalid email',
    invalidPassword: 'Invalid password',
    loginError: 'Invalid email or password',
    signUpError: 'Sign up error',
    alreadyAccount: 'Already have an account?',
    agreeTerms: 'I agree to the Terms & Conditions',
    dontHaveAccount: 'Don\'t have an account?',
    loginSuccess: 'Login successful',
    signUpSuccess: 'Sign up successful',
    logOutySuccess: 'Log out successful',
    userExists: 'Email already exists',
    emailNotExist: 'Email does not exist',
    emailExitLogin: 'User already exists, please login',
    confirmPasswordLable: 'Confirm Password',
    confirmPassword: 'confirmPassword',
    confirmPasswordRequired: 'Confirm Password is required',
    confirmPasswordPlaceholder: 'Enter your confirm password',
    invalidConfirmPassword: 'Invalid confirm password',
    passwordNotMatch: 'Password does not match',
    userNotFound: 'User not found',
    wrongPassword: 'Wrong password',
    invalidCredential: 'Invalid credential',
    userDatabaseError: 'User database error',
    weakPassword: 'Your password is too weak,please use a strong password',
    forgotPasswordHeader: 'Forgot Password',
    setPasswordtoEmail: 'A password reset link has been sent to your email',
    editProfile: 'Edit Profile',
} as const ;